name: if-1
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: get event name
      run: echo ${{ github.event_name }}
  
  job2:
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
    - name: get event name
      run: echo ${{ github.event_name }}